#!/usr/bin/env python3
"""Create gitignored .env with SESSION_SECRET + optional Stripe from charts."""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ENV_PATH = REPO / ".env"
CHARTS_SITE = Path.home() / "charts" / ".env.site"


def parse_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        if "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip("'").strip('"')
    return out


def main() -> int:
    existing = parse_env(ENV_PATH) if ENV_PATH.is_file() else {}
    charts = parse_env(CHARTS_SITE)

    session = existing.get("SESSION_SECRET") or secrets.token_urlsafe(48)
    stripe = (
        existing.get("QUANTRADAR_STRIPE_SECRET_KEY")
        or charts.get("QUANTRADAR_STRIPE_SECRET_KEY")
        or ""
    )
    public = existing.get("PUBLIC_BASE_URL") or "http://127.0.0.1:8765"
    lines = [
        "# Generated by scripts/bootstrap_env.py — do not commit",
        f"PUBLIC_BASE_URL={public}",
        "HOST=0.0.0.0",
        "PORT=8765",
        "QUANTRADAR_MODE=artifact",
        f"SESSION_SECRET={session}",
        f"QUANTRADAR_STRIPE_SECRET_KEY={stripe}",
        f"GOOGLE_CLIENT_ID={existing.get('GOOGLE_CLIENT_ID', '')}",
        f"GOOGLE_CLIENT_SECRET={existing.get('GOOGLE_CLIENT_SECRET', '')}",
        f"STRIPE_PRICE_ID={existing.get('STRIPE_PRICE_ID', '')}",
        f"SMTP_HOST={existing.get('SMTP_HOST', '')}",
        f"SMTP_PORT={existing.get('SMTP_PORT', '587')}",
        f"SMTP_USER={existing.get('SMTP_USER', '')}",
        f"SMTP_PASS={existing.get('SMTP_PASS', '')}",
        f"SMTP_FROM={existing.get('SMTP_FROM', '')}",
        "QUANTRADAR_DEV_LOGIN=1",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {ENV_PATH}")
    print(f"  SESSION_SECRET: set (len={len(session)})")
    print(f"  STRIPE: {'yes' if stripe else 'no'}")
    print(f"  GOOGLE: {'yes' if existing.get('GOOGLE_CLIENT_ID') else 'no (use magic link)'}")
    print("Next:")
    print("  python3 -m app")
    print("  open http://127.0.0.1:8765/login  → email magic link")
    print("Deploy: set same keys on Render/Fly; see docs/DEPLOY.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
